auth:
  database: ${DB_DATABASE}
  password: ${DB_USER_PASSWORD}
  username: ${DB_USER_USERNAME}
  postgresPassword: ${DB_ROOT_PASSWORD}
  enablePostgresUser: true

storageClass: netapp-block-standard

primary:
  podSecurityContext:
    fsGroup: 1003230000
  containerSecurityContext:
    runAsUser: 1003239999
  persistence:
    size: "1Gi"
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"

volumePermissions:
  containerSecurityContext:
    runAsUser: 1003239999


readReplicas:
  podSecurityContext:
    fsGroup: 1003230000
  containerSecurityContext:
    runAsUser: 1003239999 
