version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
      image: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      build:
        context: ./keycloak/
        dockerfile: Dockerfile
      command: ["start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"]
      volumes:
        - ./keycloak/extensions/themes/src/main/resources/theme/bcgov:/opt/keycloak/themes/bcgov
        - ./keycloak/extensions/themes/src/main/resources/theme/bcgov-idp-stopper:/opt/keycloak/themes/bcgov-idp-stopper
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres
  dummy:
      build:
        context: .
        dockerfile: Dockerfile.dummy
      ports:
      - "3000:3000"
