variable "dev_client_id" { }
variable "dev_client_secret" { }
variable "dev_username" { }
variable "dev_password" { }
variable "dev_keycloak_url" { }
variable "test_client_id" { }
variable "test_client_secret" { }
variable "test_username" { }
variable "test_password" { }
variable "test_keycloak_url" { }
variable "prod_client_id" { }
variable "prod_client_secret" { }
variable "prod_username" { }
variable "prod_password" { }
variable "prod_keycloak_url" { }
variable "test_siteminder_signing_certificate" { }
variable "prod_siteminder_signing_certificate" { }