name: Apply terraform plan

on:
  push:
    branches:
      - main
      - dev
      - feature/terraform-setup

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_DB_ROOT_PASSWORD: ${{ secrets.TF_VAR_DB_ROOT_PASSWORD }}
      TF_VAR_DB_USER_PASSWORD: ${{ secrets.TF_VAR_DB_USER_PASSWORD }}
      TF_VAR_DB_USER_USERNAME: ${{ secrets.TF_VAR_DB_USER_USERNAME }}
      TF_VAR_KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.TF_VAR_KEYCLOAK_ADMIN_PASSWORD }}
      TF_VAR_KEYCLOAK_ADMIN_USERNAME: ${{ secrets.TF_VAR_KEYCLOAK_ADMIN_USERNAME }}
      TF_VAR_SUB_DOMAIN: ${{ secrets.TF_VAR_SUB_DOMAIN }}
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: Create Kube Config
        run: |
          echo "${{secrets.KUBE_CONFIG}}" > ./kubeconfig
      - name: set kube-config
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: ${{ secrets.KUBE_CONTEXT }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          backend_config: |
            username=${{secrets.ARTIFACTORY_USERNAME}}
            password=${{secrets.ARTIFACTORY_PASSWORD}}
            url=${{secrets.ARTIFACTORY_URL}}
            repo=${{secrets.ARTIFACTORY_REPO}}
            subpath=${{secrets.ARTIFACTORY_SUBPATH}}
