name: Runs Demo applications terraform plan
on:
  pull_request:
    branches:
      - "main"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_DOCKER_USERNAME: ${{ secrets.TF_VAR_DOCKER_USERNAME }}
      TF_VAR_DOCKER_PASSWORD: ${{ secrets.TF_VAR_DOCKER_PASSWORD }}
      TF_VAR_DOCKER_EMAIL: ${{ secrets.TF_VAR_DOCKER_EMAIL }}
      TF_VAR_DOCKER_IMAGE: ${{ secrets.TF_VAR_DOCKER_IMAGE }}
      TF_VAR_KEYCLOAK_AUTHORITY: ${{ secrets.TF_VAR_KEYCLOAK_AUTHORITY }}
      TF_VAR_APP_1_KEYCLOAK_CLIENT_ID: ${{ secrets.TF_VAR_APP_1_KEYCLOAK_CLIENT_ID  }}
      TF_VAR_APP_1_KEYCLOAK_CLIENT_SECRET: ${{  secrets.TF_VAR_APP_1_KEYCLOAK_CLIENT_SECRET }}
      TF_VAR_APP_2_KEYCLOAK_CLIENT_ID : ${{  secrets.TF_VAR_APP_2_KEYCLOAK_CLIENT_ID }}
      TF_VAR_APP_2_KEYCLOAK_CLIENT_SECRET : ${{  secrets.TF_VAR_APP_2_KEYCLOAK_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Create Kube Config
        run: |
          echo "${{secrets.KUBE_CONFIG}}" > ./terraform/demo-app/kubeconfig

      - name: terraform demo-app plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/demo-app
          backend_config: |
            username=${{ secrets.ARTIFACTORY_USERNAME }}
            password=${{ secrets.ARTIFACTORY_PASSWORD }}
            url=${{ secrets.ARTIFACTORY_URL }}
            repo=${{ secrets.ARTIFACTORY_REPO }}
            subpath=${{ secrets.ARTIFACTORY_DEMO_APP_SUBPATH }}