name: Apply terraform plan

on:
  push:
    branches:
      - main
      - dev

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: Create Kube Config
        run: |
          echo "${{secrets.KUBE_CONFIG}}" > ./terraform/kubeconfig
      - name: set kube-config
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: ${{ secrets.KUBE_CONTEXT }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          backend_config: |
            username=${{secrets.ARTIFACTORY_USERNAME}}
            password=${{secrets.ARTIFACTORY_PASSWORD}}
            url=${{secrets.ARTIFACTORY_URL}}
            repo=${{secrets.ARTIFACTORY_REPO}}
            subpath=${{secrets.ARTIFACTORY_SSO_SUBPATH}}
