name: Runs terraform plan
on:
  pull_request:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_DB_ROOT_PASSWORD: ${{ secrets.TF_VAR_DB_ROOT_PASSWORD }}
      TF_VAR_DB_USER_PASSWORD: ${{ secrets.TF_VAR_DB_USER_PASSWORD }}
      TF_VAR_DB_USER_USERNAME: ${{ secrets.TF_VAR_DB_USER_USERNAME }}
      TF_VAR_KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.TF_VAR_KEYCLOAK_ADMIN_PASSWORD }}
      TF_VAR_KEYCLOAK_ADMIN_USERNAME: ${{ secrets.TF_VAR_KEYCLOAK_ADMIN_USERNAME }}
      TF_VAR_SUB_DOMAIN: ${{ secrets.TF_VAR_SUB_DOMAIN }}
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Login to docker repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REPOSITORY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Echo commit GITHUB_SHA::6
        run: echo "ssag.jfrog.io/ssag:${GITHUB_SHA}"

      - name: Build Docker Image - Demo App
        uses: docker/build-push-action@v3
        with:
          file: demo-app/.docker/Dockerfile.prod
          context: ./demo-app
          push: true
          tags: ssag.jfrog.io/ssag:latest

      - name: set kube-config
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: ${{ secrets.KUBE_CONTEXT }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
          backend_config: |
            username=${{secrets.ARTIFACTORY_USERNAME}}
            password=${{secrets.ARTIFACTORY_PASSWORD}}
            url=${{secrets.ARTIFACTORY_URL}}
            repo=${{secrets.ARTIFACTORY_REPO}}
            subpath=${{secrets.ARTIFACTORY_SUBPATH}}

