name: Runs KeyCloak terraform plan
on:
  pull_request:
    branches:
      - "dev"
      - "main"
      - "BCSCP-4_Local-keycloak"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_DEV_CLIENT_ID: ${{ secrets.TF_VAR_DEV_CLIENT_ID }}
      TF_VAR_DEV_CLIENT_SECRET: ${{ secrets.TF_VAR_DEV_CLIENT_SECRET }}
      TF_VAR_DEV_KEYCLOAK_URL: ${{ secrets.TF_VAR_DEV_KEYCLOAK_URL }}
      TF_VAR_DEV_USERNAME: ${{ secrets.TF_VAR_DEV_USERNAME }}
      TF_VAR_DEV_PASSWORD: ${{ secrets.TF_VAR_DEV_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/keycloak
          backend_config: |
            username=gh_action
            password=${{secrets.ARTIFACTORY_PASSWORD}}
            url=https://ssag.jfrog.io/artifactory
            repo=ssag-terraform-be
            subpath=ssag-infrastructure-dev

