name: Runs infrastructure terraform plan
on:
  pull_request:
    branches:
      - "main"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_DB_ROOT_PASSWORD: ${{ secrets.TF_VAR_DB_ROOT_PASSWORD }}
      TF_VAR_DB_USER_PASSWORD: ${{ secrets.TF_VAR_DB_USER_PASSWORD }}
      TF_VAR_DB_USER_USERNAME: ${{ secrets.TF_VAR_DB_USER_USERNAME }}
      TF_VAR_KEYCLOAK_ADMIN_PASSWORD: ${{ secrets.TF_VAR_KEYCLOAK_ADMIN_PASSWORD }}
      TF_VAR_KEYCLOAK_ADMIN_USERNAME: ${{ secrets.TF_VAR_KEYCLOAK_ADMIN_USERNAME }}
      TF_VAR_SUB_DOMAIN: ${{ secrets.TF_VAR_SUB_DOMAIN }}
      TF_VAR_KEYCLOAK_REGISTRY_USERNAME: ${{ secrets.TF_VAR_KEYCLOAK_REGISTRY_USERNAME }}
      TF_VAR_KEYCLOAK_REGISTRY_API_KEY: ${{ secrets.TF_VAR_KEYCLOAK_REGISTRY_API_KEY }}
      TF_VAR_KEYCLOAK_REGISTRY_URL: ${{ secrets.TF_VAR_KEYCLOAK_REGISTRY_URL }}
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: Create Kube Config
        run: |
          echo "${{secrets.KUBE_CONFIG}}" > ./terraform/infrastructure/kubeconfig
      - name: set kube-config
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: ${{ secrets.KUBE_CONTEXT }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/infrastructure
          backend_config: |
            username=${{secrets.ARTIFACTORY_USERNAME}}
            password=${{secrets.ARTIFACTORY_PASSWORD}}
            url=${{secrets.ARTIFACTORY_URL}}
            repo=${{secrets.ARTIFACTORY_REPO}}
            subpath=${{secrets.ARTIFACTORY_SUBPATH}}

