name: Runs KeyCloak terraform plan
on:
  pull_request:
    branches:
      - "main"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_DEV_CLIENT_ID: ${{ secrets.TF_VAR_DEV_CLIENT_ID }}
      TF_VAR_DEV_CLIENT_SECRET: ${{ secrets.TF_VAR_DEV_CLIENT_SECRET }}
      TF_VAR_DEV_KEYCLOAK_URL: ${{ secrets.TF_VAR_DEV_KEYCLOAK_URL }}
      TF_VAR_DEV_USERNAME: ${{ secrets.TF_VAR_DEV_USERNAME }}
      TF_VAR_DEV_PASSWORD: ${{ secrets.TF_VAR_DEV_PASSWORD }}
      TF_VAR_KEYCLOAK_REGISTRY_USERNAME: ${{ secrets.TF_VAR_KEYCLOAK_REGISTRY_USERNAME }}
      TF_VAR_KEYCLOAK_REGISTRY_API_KEY: ${{ secrets.TF_VAR_KEYCLOAK_REGISTRY_API_KEY }}
      TF_VAR_KEYCLOAK_REGISTRY_URL: ${{ secrets.TF_VAR_KEYCLOAK_REGISTRY_URL }}
      TF_VAR_DEV_BCSC_CLIENT_ID: ${{ secrets.TF_VAR_DEV_BCSC_CLIENT_ID }}
      TF_VAR_DEV_BCSC_CLIENT_SECRET: ${{ secrets.TF_VAR_DEV_BCSC_CLIENT_SECRET }}
      TF_VAR_DEV_BCSC_APP_1_CLIENT_ID: ${{ secrets.TF_VAR_DEV_BCSC_APP_1_CLIENT_ID }}
      TF_VAR_DEV_BCSC_APP_1_CLIENT_SECRET: ${{ secrets.TF_VAR_DEV_BCSC_APP_1_CLIENT_SECRET }}
      TF_VAR_DEV_BCSC_APP_2_CLIENT_ID: ${{ secrets.TF_VAR_DEV_BCSC_APP_2_CLIENT_ID }}
      TF_VAR_DEV_BCSC_APP_2_CLIENT_SECRET: ${{ secrets.TF_VAR_DEV_BCSC_APP_2_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/keycloak
          backend_config: |
            username=${{ secrets.ARTIFACTORY_USERNAME }}
            password=${{ secrets.ARTIFACTORY_PASSWORD }}
            url=${{ secrets.ARTIFACTORY_URL }}
            repo=${{ secrets.ARTIFACTORY_REPO }}
            subpath=${{ secrets.ARTIFACTORY_KEYCLOAK_SUBPATH }}

